# Generated by Django 5.2.10 on 2026-02-18 01:06

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0225_gfk_indexes'),
        ('extras', '0134_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='active', max_length=30)),
                ('config', models.JSONField(default=dict)),
                ('scan_interval', models.PositiveIntegerField(default=0)),
                ('last_scan', models.DateTimeField(blank=True, null=True)),
                ('last_scan_success', models.BooleanField(default=True)),
                ('sync_devices', models.BooleanField(default=True)),
                ('sync_clients', models.BooleanField(default=True)),
                ('sync_vlans', models.BooleanField(default=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dry_run', models.BooleanField(default=False)),
                ('discovered_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('log', models.TextField(blank=True, default='')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_jobs', to='nb_udm_plugin.discoverysource')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('-created',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DiscoveryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('identity_key', models.CharField(db_index=True, max_length=255)),
                ('netbox_object_id', models.PositiveBigIntegerField()),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_orphan', models.BooleanField(default=False)),
                ('netbox_object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='nb_udm_plugin.discoverysource')),
            ],
            options={
                'ordering': ('source', 'identity_key'),
                'unique_together': {('source', 'identity_key')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DiscoveryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('discovered_type', models.CharField(max_length=50)),
                ('discovered_data', models.JSONField(default=dict)),
                ('proposed_data', models.JSONField(default=dict)),
                ('matched_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('diff', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('action', models.CharField(default='create', max_length=30)),
                ('identity_key', models.CharField(db_index=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('matched_object_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='nb_udm_plugin.discoverysource')),
                ('scan_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='nb_udm_plugin.scanjob')),
            ],
            options={
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['source', 'identity_key'], name='nb_udm_plug_source__ee556d_idx'), models.Index(fields=['status'], name='nb_udm_plug_status_e3f417_idx')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
